### ISSUE TITLE
Using `\*` within the title regex appears to cause a failure.

### ISSUE THREAD

**Issue by shellscape** [clowdhaus/actions#15]
### Describe the bug

Using `\*` within the title regex appears to cause a failure.

### To Reproduce

Using this config:

```
      - name: Check PR Title
        uses: clowdhaus/actions/pr-title
        with:
          on-fail-message: "Your PR title doesn't match the required format. The title should be in the conventional commit (https://www.conventionalcommits.org/en/v1.0.0-beta.4/) format. e.g.\n\n```\nchore: add pr title workflow\n```. Note that scopes should not contain spaces."
          title-regex: '^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\((\*|[\w|,|\-|\|]+)\))?(!)?\:\s.*'
          github-token: ${{ secrets.GITHUB_TOKEN }}
```

Attempt to validate a PR title of `fix(*): use tsup (again) to produce compatible esm and cjs builds`

### Expected behavior

As evidenced by testing the regex manually:

```ts
/^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\((\*|[\w|,|\-|\|]+)\))?(!)?\:\s.*/.test('fix(*): use tsup (again) to produce compatible esm and cjs builds')
```

The regular expression is valid and the PR title provided as an example passes test. The workflow shouldn't be failing.

### Screenshots

n/a

## Environment (please complete the following information):

A failing workflow can be seen here: https://github.com/shellscape/jsx-email/actions/runs/6595077760/job/17919681726?pr=42#step:3:6
